language: generic
cache: apt
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: CXX=g++-5
    - compiler: nvcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - nvidia-cuda-dev nvidia-profiler nvidia-cuda-toolkit
      env: NVCC=nvcc
script:
  - make
  - make test
